spring:
  datasource:
    url: jdbc:mysql://product-db.c95ieyp3exq5.us-east-2.rds.amazonaws.com:3306/product_db
    username: root
    password: root1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
