name: product_microservice

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      env: 
        SONAR_URL: https://sonarcloud.io  
        SONAR_LOGIN: b6e807db59e81eaf343f0a58d41307255595928b
        SONAR_PROJECT_KEY: product_ms
        SONAR_ORGANIZATION: ekart-product 
      run: mvn -B clean package -DskipTests -D"sonar.host.url"=SONAR_URL -D"sonar.organization"=SONAR_ORGANIZATION -D"sonar.projectKey"=SONAR_PROJECT_KEY -D"sonar.login"=SONAR_LOGIN
    - name: Verify with Sonar
      env: 
        SONAR_URL: https://sonarcloud.io  
        SONAR_LOGIN: b6e807db59e81eaf343f0a58d41307255595928b
        SONAR_PROJECT_KEY: product_ms
        SONAR_ORGANIZATION: ekart-product 
      run: mvn -B verify sonar:sonar -D"sonar.host.url"=SONAR_URL -D"sonar.organization"=SONAR_ORGANIZATION -D"sonar.projectKey"=SONAR_PROJECT_KEY -D"sonar.login"=SONAR_LOGIN
    
    services:
      mysql:
          image: mysql:5.7
          env:
              MYSQL_ALLOW_EMPTY_PASSWORD: yes
              MYSQL_DATABASE: product_db
          ports:
              - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
